pipeline {
    agent any

    stages {
        stage('EOL') {
            steps {
                sh """#!/bin/bash -xe
                    echo "hello From CPP Check"
                    sleep 2
                    """
            }
        }
    }
}
