pipeline {
    agent {
        label 'build'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checkout Step'
            } // steps
        } // stage: Checkout

        stage('Check') {
            agent {
                dockerfile {
                    dir 'yocto-layers/docker/native'
                    filename 'Dockerfile'
                    reuseNode true
                    args '-v/var/lib/jenkins/yocto:/var/lib/jenkins/yocto'
              } // dockerfile
            } // agent

            steps {
                sh """#!/bin/bash -xe
                  echo 'cppcheck'
                """
            } // steps
        } // Stage: Check
    } // stages
} // pipeline
